### ISSUE TITLE
Change the the entity_type kwarg to table_name

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/Flask-JWT-Router#111]
Our API has 2 public methods, one of which is `register_entity`. This currently requires a kwarg of `entity_type` to donate the table name, which is confusing to the user.

Change `register_entity` method's kwarg of `entity_type` to `table_name`. This may result in updating other parts of the codebase, docs, README, blog and tests.

**Comment by kousikmitra** [comment]
Or should we change it to `entity_name` since it's more relevant to the context. We are also using `register_entity`  as function name.

**Comment by joegasewicz** [comment]
Yea that’s a valid observation but for the work involved I’m not sure it’s worth the effort at the moment to change just a prefix of an existing kwarg. I have had some complaints from devs looking at this library and not understanding what “entity” represents... maybe we should change the method name and therefore also change the Kwangju to table_name then to make more sense?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kousikmitra** [comment]
yes at first I also couldn't understood what `entity` represents here. But since we are using Flask models then isn't it better if we change the names to `model_name` and `register_model`?

**Comment by joegasewicz** [comment]
Ok, thats much better. Let's go with `model_name` as the kwarg and `register_model` as the method name. 

I also need to update the other public method name to ` update_token` - ( i don't think we should call it `update_model` because it's not updating the model).

**Comment by joegasewicz** [comment]
@kousikmitra  Let's go with table_name as the kwarg and register_model as the method name.

**Comment by kousikmitra** [comment]
@joegasewicz can we derive the table name from the model name? Then the user can just pass the model_name to the function and we can get the table_name from there. Since when people use Models they don't give much attention to table_name(own perspective)

**Comment by joegasewicz** [comment]
The problem is, is that we have to handle multiple models , so we have to know which model the user wants to append to Flask's global context.

```
app.config["ENTITY_MODELS"] = [ UserModel, TeacherModel, ...etc ]
```

**Comment by kousikmitra** [comment]
> 
> 
> The problem is, is that we have to handle multiple models , so we have to know which model the user wants to append to Flask's global context.
> 
> ```
> app.config["ENTITY_MODELS"] = [ UserModel, TeacherModel, ...etc ]
> ```

Okay I will look into the code and will revert back to you. or we will go with the `table_name` approach for now.

**Comment by joegasewicz** [comment]
No problem @kousikmitra 

The win is that you don't need to import your models for your - User for example , into every module that  calls the `register_entity` method. 

The Loose is that it could confuse devs using this library..

For me personally, I'm always aware of the table name as i normally create the tables by hand to understand the data. But, i know some developers might only ever use the ORM & not be too familiar with whats inside the database, even if that's not a good habit lol

We could pass in the Model then directly to the `register_entity` but then every time we need to return a new token then we also need to pass in that Model class.

**Comment by joegasewicz** [comment]
In fact we only need 1 method as we are only every updating from the model..

**Comment by joegasewicz** [comment]
@kousikmitra Im going to close this issue and open a few new ones tomorrow to carry out this work, I have to go out now to play some music but will be back in the morning UK time, feel free to open an issue and start working on it, if we can split this work up as much as possible as it's non trivial.
thanks
Joe

**Comment by joegasewicz** [comment]
@kousikmitra I've reopened & updated this issue if you still want to work on it.
