### ISSUE TITLE
Look into OAuth & perhaps we can wrap this strategy in a separate class / strategy / algorithm etc.

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/Flask-JWT-Router#132]

**Comment by kousikmitra** [comment]
What is this feature is about?

**Comment by joegasewicz** [comment]
It's a non trivial protocol: https://en.wikipedia.org/wiki/OAuth

**Comment by joegasewicz** [comment]
> What is this feature is about?

It's a non trivial protocol: https://en.wikipedia.org/wiki/OAuth ... 

This issue is just too look into the OAuth protocol and see which parts we could incorporate into our library.

**Comment by joegasewicz** [comment]
Sorry @kousikmitra this is a bit far fetched this story, my bad, OAuth is more than a library is a server etc etc.. so im going to close this issue. Thanks
