### ISSUE TITLE
Outdated docstring - nice easy fix for a beginner developer!

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/flask-jwt-router#192]
`Therefore we have provided a utility method that returns a headers Dict that you can then use in your test view handler request.` Should be:
`
Therefore we have provided a utility method that you can then use in your test view handler request.
`

here: 
https://github.com/joegasewicz/flask-jwt-router/blob/e6e5bad9d5a3ecaff51279a05fa8a24e8cc44de8/flask_jwt_router/oauth2/google.py#L95

here (should return `-> str`):

https://github.com/joegasewicz/flask-jwt-router/blob/e6e5bad9d5a3ecaff51279a05fa8a24e8cc44de8/flask_jwt_router/oauth2/google.py#L248

here (Should just return `Bearer your@email.com`):
https://github.com/joegasewicz/flask-jwt-router/blob/e6e5bad9d5a3ecaff51279a05fa8a24e8cc44de8/flask_jwt_router/oauth2/google.py#L266

**Comment by jpcarroll** [comment]
Hi @joegasewicz I would like to work on this issue!

**Comment by joegasewicz** [comment]
Please go ahead @jpcarroll

**Comment by jpcarroll** [comment]
PR for changes [here](https://github.com/joegasewicz/flask-jwt-router/pull/196) @joegasewicz
