### ISSUE TITLE
Returning 401 on any unauthorised routes

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/Flask-JWT-Router#47]
The bug fix needs to make sure 404's get returned on routes that don't exist (no request handlers for these routes).

**Comment by kousikmitra** [comment]
hey is this issue still open? I would like to work on this.

**Comment by joegasewicz** [comment]
Hi @kousikmitra yes , still open, please go ahead.

**Comment by joegasewicz** [comment]
In `test_routing.py` line 106 , `/apples/sub/hello` route isn't handled by a request handler and also its not whitelisted / ignored. So therefore it should return a 404 but currently the test asserts a 401.
```
        rv = test_client.get("/api/v1/apples/sub/hello")
        assert "401" in str(rv.status)
```

**Comment by joegasewicz** [comment]
I use pipenv to run the tests, so once you set up your pipenv environment `pipenv shell` you can run the tests with `pipenv run pytest -vv`

**Comment by kousikmitra** [comment]
Therefore I need to add a check where it will check if the route is present or not and based on that if the route is not present it should return 404. right?

**Comment by joegasewicz** [comment]
yes, this link might help:
https://stackoverflow.com/questions/13317536/get-list-of-all-routes-defined-in-the-flask-app

**Comment by kousikmitra** [comment]
OK. I understood. I will ask you if I need anything else. :)

**Comment by kousikmitra** [comment]
@joegasewicz what are you using to debug the application and how?

**Comment by joegasewicz** [comment]
@kousikmitra you should be able to create a pipenv environment, and then run the commands i listed above. So you probably don't need to run the debugger directly, its more a case starting the test suite with `pipenv run pytest -vv` and you mainly need to run tyhat single unit test:
https://github.com/joegasewicz/Flask-JWT-Router/blob/8a273366aaceeb4e21938f2cdb69257a74d584d4/tests/test_routing.py#L103

you can actually add a pytest mark to run just this single test and comment out the assertion u dont need:
```
   @pytest.mark.j
    def test_dynamic_params(self, test_client):
       #  rv = test_client.put("/api/v1/apples/sub/1")
        # assert "200" in str(rv.status)

        rv = test_client.get("/api/v1/apples/sub/")
        assert "401" in str(rv.status)
```
and run with `pipenv run pytest -vv -m j

**Comment by kousikmitra** [comment]
Hi @joegasewicz I was working on this today but got a problem.
I am able to fix the issue by checking whether a route exist for the requested URL by using this function,
   

      def _is_route_exist(self, url: str, method: str) -> bool:
          adapter = self.app.url_map.bind('')
          try:
              adapter.match(url, method=method)
          except RequestRedirect as e:
              # recursively match redirects
              return self._is_route_exist(e.new_url, method)
          except (MethodNotAllowed, NotFound):
              # no match
              return False
          return True

But the problem is this fix is failing another test case.

    def test_before_middleware(self, monkeypatch, TestMockEntity, mock_token):
         app = Flask(__name__)
         # Manually set the primary key
         entity = TestMockEntity(id=1, user_name="joe")
         ctx = app.test_request_context("/test")
         ctx.push()
         assert entity.user_name == "joe"
         assert entity.id == 1
         self.ext.entity_models = [TestMockEntity]
         entity = Entity(self.ext)
         routing = Routing(app, self.ext, entity)
         with ctx: 
         # token from args
             monkeypatch.setattr("flask.request.args", MockArgs(mock_token))
             routing.before_middleware()
     assert ctx.g.test_entities == [(1, 'joe')]    E   AttributeError: '_AppCtxGlobals' object has no attribute 'test_entities'
     tests\test_routing.py:66: AttributeError

Do you have any idea why is it failing. I have checked that whenever the we are not passing the handle to `_handle_token` method this error is happening.

**Comment by joegasewicz** [comment]
Cool @kousikmitra ok il look into this ...

**Comment by joegasewicz** [comment]
@kousikmitra can you create a pull request and then i can pull your code down and run the tests locally, thanks 👍

**Comment by kousikmitra** [comment]
@joegasewicz  I have created the pull request. Looks like the `Pipfile.lock` has been modified because I was using flake8 for linting. Its not removed from the lock file. Please revert back to me if there any fix is needed.

**Comment by joegasewicz** [comment]
@kousikmitra thanks for your efforts, i added a few comments.
