### ISSUE TITLE
remove 's' from entity on g context

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/Flask-JWT-Router#90]
when the entity data is assigned to Flask global context it can derive from a plural table entity name (especially if the user uses the __tablename__ attribute). So removing the 's' makes it clearer when returning the global context entity value

```
user = g.user 3 . # not g.users 
```

**Comment by kousikmitra** [comment]
hey @joegasewicz is this issue still open?

**Comment by joegasewicz** [comment]
Hi @kousikmitra yes go ahead, thank you 👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kousikmitra** [comment]
@joegasewicz can you give a brief? I couldn't find anything like that in the source code.

**Comment by joegasewicz** [comment]
@kousikmitra Sure thing. Currently, we append our entity object onto Flask's global context:
https://github.com/joegasewicz/Flask-JWT-Router/blob/3e3b04f93d44ed0bd6bedad3bca67aa5e0217521/flask_jwt_router/_routing.py#L185
So now we have access to the entity via the database table name:
`users` for example.
This issue is about check if the last letter is an `s` & if it is then stripping off that `s` so then we would be able to access our entity off of Flask's global context like this:
`g.user` 
The reason is that this library is only working with a single entity, so it might be confusing to keep  assigning a plural named attribute to `g`

thanks
Joe

**Comment by joegasewicz** [comment]
@kousikmitra Sorry, also since yoour last PR, i added linting and also testing on python 3.6, 3.7 & 3.8.
You can now run `tox` & as long as you have those 3 versions of python installed then it will give you tests & linting .

Of course, you can still run pytest with pip of pipenv and then push your code up & then tox will get run on the repo. Also , if you do it like this you will probably need top run pylint as well, although like i said this does get run with tox on the repo.
thanks
Joe

**Comment by kousikmitra** [comment]
But @joegasewicz what if any table has `s` not as in plural but as normal English word? Should we just remove the `s` in that case too?

**Comment by joegasewicz** [comment]
@kousikmitra good point but its very unlikely because the resource name should be a noun & there's only 2 nouns with 's' 
- bus
- lens

http://www.focus.olsztyn.pl/en-grammar-nouns-uncountable-s.html
if users of this library do want to use these nouns, im sure we can open an issue to add some kwargs to the main API methods we offer (update_entity & register_entity etc)

thank you 
Joe

**Comment by kousikmitra** [comment]
Okay it looks alright. I didn't knew this fact. 😸

**Comment by kousikmitra** [comment]
@joegasewicz there's another issue. There is test function in which it has a keyword `test_entities` in this case the name ends with `s` but just removing the `s` doesn't sounds good. So in this type of nouns there will be the same problem.

**Comment by joegasewicz** [comment]
@kousikmitra good spot. Can we rename that as well, here are the places to fix:

https://github.com/joegasewicz/Flask-JWT-Router/blob/3e3b04f93d44ed0bd6bedad3bca67aa5e0217521/tests/test_routing.py#L70

https://github.com/joegasewicz/Flask-JWT-Router/blob/3e3b04f93d44ed0bd6bedad3bca67aa5e0217521/tests/test_routing.py#L77

https://github.com/joegasewicz/Flask-JWT-Router/blob/3e3b04f93d44ed0bd6bedad3bca67aa5e0217521/tests/fixtures/model_fixtures.py#L23

https://github.com/joegasewicz/Flask-JWT-Router/blob/3e3b04f93d44ed0bd6bedad3bca67aa5e0217521/tests/fixtures/model_fixtures.py#L39

https://github.com/joegasewicz/Flask-JWT-Router/blob/3e3b04f93d44ed0bd6bedad3bca67aa5e0217521/tests/fixtures/token_fixture.py#L8

The tests should now be able to take a noun such as `users` as a table name and then we should assert we have `g.user`. If there is no `s` in the table name then we dont need to update it. 

Pick any name you like to replace `test_entities` for example `uers` `teachers` `admins`

**Comment by joegasewicz** [comment]
@kousikmitra sorry, i edited the above comment to reconsider your point about words ending in 'ies'. thanks

**Comment by kousikmitra** [comment]
@joegasewicz ya this sounds good. Cause I am really not feeling this will be a good way of doing this.

**Comment by joegasewicz** [comment]
@kousikmitra perfectly understand, thanks for looking into this for now.
this is the code i currently use to work around this:
```
        if "teachers" not in g:
            return abort(401)
        teacher = g.teachers
```

**Comment by joegasewicz** [comment]
Maybe we should change the public API to make it more obvious that the entity_type is derived from the table name and not use `entity_type`

**Comment by joegasewicz** [comment]
Closing this as , as we now have renamed `entity_key` to `table_name` it makes this issue redundant.
