### ISSUE TITLE
Throw exception if user hasn't passed a valid entity_type

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/Flask-JWT-Router#91]
https://github.com/joegasewicz/Flask-JWT-Router/blob/8a273366aaceeb4e21938f2cdb69257a74d584d4/flask_jwt_router/_authentication.py#L92

Check if `entity_type` kwarg exists, if not throw with a meaningful message to the user.

**Comment by joegasewicz** [comment]
Also please update with tests.

**Comment by kousikmitra** [comment]
what about this one @joegasewicz ?

**Comment by joegasewicz** [comment]
@kousikmitra Yes this is available, please go ahead. 
Just an update:
This should throw an exception message back to the user to inform them to declare a entity_type kwarg when calling our API's `register_entity` method
```
jwt_routes.register_entity(entity_id=student.student_id, entity_type="students")
```

**Comment by joegasewicz** [comment]
This work has been merged.
